### ISSUE TITLE
Unstoppable 

### ISSUE THREAD

**Issue by orange-toothbrush** [sethforprivacy/sethforprivacy.com#12]
Post: https://github.com/sethforprivacy/sethforprivacy.com/blob/master/content/guides/bitcoin-monero-atomic-swaps.md

https://unstoppableswap.net has taken down the web UI while it is underdevelopment. From the site:

"Web UI has been disabled

The functionality of this website has been deprecated and will be removed entirely in the future. It will soon be replaced by a desktop app that is currently in active development. The GitHub repository is public, so feel free to inspect the code or provide feedback as development progresses."

At this point it's probably best to suggest CLI swaps only

**Comment by sethforprivacy** [comment]
Archived this post as it's wildly out of date anyways.
