### ISSUE TITLE
Where to register the Bitcoin_RPC and Bitcoin_RPC_Password on Public-Pool.IO?

### ISSUE THREAD

**Issue by gusevargas** [sethforprivacy/sethforprivacy.com#31]
Hi SethforPrivacy,
 I tried running the bitcoind files, I do not get the expected message of Bitcoin RPC Connected or Stratum server listening on port 3333.
It is perhaps related to having the BITCOIN_RPC and BITCOIN_RPC_PASSWORD variables get setup or registered within the Public-Pool.IO?
Thank you in advance.

![image](https://github.com/user-attachments/assets/ff379b8c-702c-4322-a919-4254c32483de)

**Comment by sethforprivacy** [comment]
This is all covered in the guide, please re-read through it before opening more issues :)

https://sethforprivacy.com/guides/run-your-own-bitcoin-pool/
