### ISSUE TITLE
Wrong URL in Foss Donations

### ISSUE THREAD

**Issue by elibroftw** [sethforprivacy/sethforprivacy.com#4]
https://github.com/sethforprivacy/sethforprivacy.com/blob/master/content/posts/foss-donations.md?plain=1#L95 contains the old github URL.

Also could you add in [Music Caster](https://github.com/elibroftw/music-caster/)? I asked you a year ago but you didn't respond.

**Comment by sethforprivacy** [comment]
Thanks, will add Music Caster and fix that URL!
